version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_biblioteca
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Monta el script de inicialización
      - ./bdBiblioteca.sql:/docker-entrypoint-initdb.d/bdBiblioteca.sql
    networks:
      - biblioteca_network

volumes:
  postgres_data:
    driver: local

networks:
  biblioteca_network:
    driver: bridge
